### ISSUE TITLE
API call in Swaggerhub fails

### ISSUE THREAD

**Issue by bartcant** [streetcred-id/iiw-demo#11]
Upon calling the

POST /definitions/credentials/{SchemaId} endpoint in swaggerhub

I get the following 500 error

{
  "error": "A storage error occurred during the wallet operation.",
  "errorType": "WalletStorageException"
}

There is no issue with executing an API call for other schema ids

**Comment by MattNorton25** [comment]
Which schema ID are you using? Trying to replicate.

**Comment by bartcant** [comment]
NGZRy3B7HgE4RpBJpzjM5y:2:business-card:1.0

**Comment by MattNorton25** [comment]
![image](https://user-images.githubusercontent.com/29149926/83415520-66242980-a3dc-11ea-9218-392996dad057.png)
Working for me, is it still causing you issues?

**Comment by bartcant** [comment]
I figured it out. 

You have to change the "Tag" value in the Body to something different than the default. Then it worked for me.
